### ISSUE TITLE
Micro 850

### ISSUE THREAD

**Issue by dcabrerag** [kodaman2/pylogix-tester#1]
Hello, thanks for the app, i tried connection with AB Micro850 and it shows my 850 and hmi pv800 ip address, revision, model and serial. 
In the last step it says:

Traceback (most recent call last):
  File "C:\Users\CanrigAdmin\Documents\git\pylogix-tester\pylogix-tester.py", line 162, in <module>
  File "C:\Python\Python34-32\lib\site-packages\pylogix\eip.py", line 112, in GetPLCTime
  File "C:\Python\Python34-32\lib\site-packages\pylogix\eip.py", line 379, in _getPLCTime
ValueError: Failed to get PLC time: Service not supported
[16132] Failed to execute script pylogix-tester

So this means my model is not supported for pylogix?

Thanks

**Comment by TheFern2** [comment]
Not necessarily, it looks like perhaps getplctime is not supported on micro800. Can you run the script again, but comment out line 162.

Line 162:

```
# print(comm.GetPLCTime())
```
Please let me know if you are able to read a tag after doing that.

**Comment by TheFern2** [comment]
Try the latest please https://github.com/kodaman2/pylogix-tester/releases/tag/v1.0.2

**Comment by dcabrerag** [comment]
wow, its working, got the temperature tag info from micro850, no errors. Thanks. Is there a way you can share the pylogix code to get this data? im trying to get the temperature from 5 sensors, i have the tags. Tried node-red but i need a python script to start. Hope you can help, Thanks for your work on this.

**Comment by TheFern2** [comment]
Awesome. If you read the readme  on pylogix it has a small example it should get you going. Also inside the pylogix package there's a folder with plenty of examples. Just make sure to set the micro800 property to True as explained in the readme. Also fyi pylogix can only read global variables. 

https://github.com/dmroeder/pylogix

**Comment by TheFern2** [comment]
This issue has been fixed on a21b042c57ebab0d35f6bc936980c8d9b12023e0, and released a new exe for it.
